trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd "$(Build.SourcesDirectory)\Typescript"
    npm ci
  displayName: 'npm install'

- script: |
    cd "$(Build.SourcesDirectory)\Typescript"
    npx playwright install chromium
  displayName: 'Install Playwright Chromium'

- script: |
    cd "$(Build.SourcesDirectory)\Typescript"
    npx playwright test
  displayName: 'Run Playwright tests'

- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: '$(Build.SourcesDirectory)\Typescript\playwright-report'
    artifact: 'playwright-report'
  displayName: 'Publish Playwright Report'